# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - nightly
notifications:
  email: false
before_script:
  - export PATH=$PATH:$HOME/.cargo/bin
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - curl https://sh.rustup.rs -sSf | sh -s -- -y
  - julia -e 'Pkg.clone(pwd()); Pkg.build("Rust"); Pkg.test("Rust"; coverage=true)'
after_success:
  # push coverage results to Codecov
  - julia -e 'cd(Pkg.dir("Rust")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
